# Generated by Django 5.2 on 2025-04-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Politics', 'Politics'), ('Technology', 'Technology'), ('Sports', 'Sports'), ('Entertainment', 'Entertainment'), ('Education', 'Education'), ('Others', 'Others')], default='Others', max_length=50),
        ),
    ]
